version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    links:
      - db

  redis:
    image: redis
    restart: 'on-failure'
    ports:
      - 6379:6379
    volumes:
      -  ./redisdb/:/var/lib/redis  