# Generated by Django 2.2.7 on 2019-12-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20191204_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='recipes')),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='stories.Category')),
            ],
            options={
                'verbose_name': 'Resept',
                'verbose_name_plural': 'Reseptler',
                'ordering': ('-created_at',),
            },
        ),
    ]
