# Generated by Django 2.2.8 on 2020-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View count'),
        ),
        migrations.AddField(
            model_name='story',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View count'),
        ),
    ]
